In [75]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import matplotlib.ticker as ticker
from sklearn import preprocessing

df = pd.read_excel(r'C:\Users\Rif010\Desktop\Clustering\Cluster.xlsx', sheet_name="People Records")
df.head()

Name                   Place name       Place type SuperType
0  Kevin Vasquez                Diaz-Anderson    travel agency    Travel
1            NaN       Wong, Myers and Peters         hospital    Health
2            NaN             Malone-Mcconnell  physiotherapist    Health
3            NaN             Frazier-Alvarado          rv park     Store
4            NaN  Sweeney, Jones and Reynolds           lawyer   Service

In [76]:
df.shape

(10001, 4)

In [77]:
df.drop('Name',1, inplace=True)
df.head()

Place name       Place type SuperType
0                Diaz-Anderson    travel agency    Travel
1       Wong, Myers and Peters         hospital    Health
2             Malone-Mcconnell  physiotherapist    Health
3             Frazier-Alvarado          rv park     Store
4  Sweeney, Jones and Reynolds           lawyer   Service

In [78]:
df.head(10)

Place name       Place type   SuperType
0                Diaz-Anderson    travel agency      Travel
1       Wong, Myers and Peters         hospital      Health
2             Malone-Mcconnell  physiotherapist      Health
3             Frazier-Alvarado          rv park       Store
4  Sweeney, Jones and Reynolds           lawyer     Service
5                Dyer and Sons  veterinary care      Health
6                Carson-Morgan        synagogue   Religious
7                    Joyce-Fox       shoe store       Store
8   Calhoun, Bradshaw and Ruiz           bakery        Food
9            Stephens-Jacobson           casino  Recreation

In [79]:
df.groupby(['Place type'])['SuperType'].value_counts(normalize=True)

Place type       SuperType 
airport          Travel        1.0
amusement park   Recreation    1.0
aquarium         Recreation    1.0
art gallery      Recreation    1.0
atm              Finance       1.0
                              ... 
train station    Travel        1.0
transit station  Travel        1.0
travel agency    Travel        1.0
veterinary care  Health        1.0
zoo              Recreation    1.0
Name: SuperType, Length: 89, dtype: float64

In [80]:
df.groupby(['SuperType'])['Place type'].value_counts()

SuperType  Place type      
Finance    bank                123
           atm                  80
           insurance agency     62
Food       bakery              175
           cafe                 92
                              ... 
Travel     airport             105
           gas station          89
           campground           72
           bus station          67
           subway station       48
Name: Place type, Length: 89, dtype: int64

In [81]:

Feature = pd.get_dummies(df['Place type'])
Feature.head()

airport  amusement park  aquarium  art gallery  atm  bakery  bank  bar  \
0        0               0         0            0    0       0     0    0   
1        0               0         0            0    0       0     0    0   
2        0               0         0            0    0       0     0    0   
3        0               0         0            0    0       0     0    0   
4        0               0         0            0    0       0     0    0   

   beauty salon  bicycle store  ...  store  subway station  supermarket  \
0             0              0  ...      0               0            0   
1             0              0  ...      0               0            0   
2             0              0  ...      0               0            0   
3             0              0  ...      0               0            0   
4             0              0  ...      0               0            0   

   synagogue  taxi stand  train station  transit station  travel agency  \
0          0           0              0                0              1   
1          0           0              0                0              0   
2          0           0              0                0              0   
3          0           0              0                0              0   
4          0           0              0                0              0   

   veterinary care  zoo  
0                0    0  
1                0    0  
2                0    0  
3                0    0  
4                0    0  

[5 rows x 89 columns]

In [82]:
y = df['SuperType'].replace(to_replace=['Finance','Food','Health','Job','Luxury','Recreation','Religious','Service','Store','Study','Travel'], value=[1,2,3,4,5,6,7,8,9,10,11]).values
y[0:10]

array([11.,  3.,  3.,  9.,  8.,  3.,  7.,  9.,  2.,  6.])

In [83]:
X=Feature
X= preprocessing.StandardScaler().fit_transform(X)
X[0:5]

array([[-0.10300654, -0.06415969, -0.10399344, -0.11565127, -0.08979813,
        -0.13345371, -0.11158814, -0.06797642, -0.13614512, -0.14857525,
        -0.0999899 , -0.10973649, -0.08212499, -0.09635605, -0.08515565,
        -0.08808501, -0.09635605, -0.08212499, -0.12422978, -0.11386242,
        -0.08865961, -0.11431212, -0.11112798, -0.09258512, -0.09203425,
        -0.08633897, -0.11250309, -0.11741428, -0.05840597, -0.09036217,
        -0.10250968, -0.09475767, -0.10594082, -0.06336924, -0.12871833,
        -0.11204651, -0.09475767, -0.1054572 , -0.11609439, -0.08923062,
        -0.11431212, -0.11158814, -0.12171612, -0.07898134, -0.13953469,
        -0.12086731, -0.08515565, -0.13538121, -0.10448354, -0.04246252,
        -0.14211931, -0.08865961, -0.09635605, -0.08979813, -0.09148018,
        -0.07637571, -0.11785113, -0.07571063, -0.12171612, -0.12381417,
        -0.12339725, -0.12710332, -0.11386242, -0.10150897, -0.11520652,
        -0.12297899, -0.10399344, -0.11697588, -0.1

In [84]:
X_train,y_train = X,y
X_train.shape

(10001, 89)

In [102]:

df.fillna(df.mean())
df.dropna()
print(df.isnull().sum())

Place name    1
Place type    1
SuperType     1
dtype: int64


In [85]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split (X, y, test_size = 0.21 ,random_state = 2)
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape


((7900, 89), (7900,), (2101, 89), (2101,))

In [86]:
y

array([11.,  3.,  3., ...,  4.,  6., nan])

In [87]:
K=20
mean_acc = np.zeros((K-1))


for n in range (1,K):
    neig = KNeighborsClassifier(n_neighbors = n).fit(X_train,Y_train)
    y_hat = neig.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(Y_test,y_hat)
    
print(mean_acc)

print("\n\nThe best accuracy is ",mean_acc.max(), "where the number of neighbors is ",mean_acc.argmax()+1)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').