In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel(r'C:\Users\Rif010\Desktop\Clustering\Cluster.xlsx', sheet_name="People Records")
df.head()

Name                   Place name       Place type SuperType
0  Kevin Vasquez                Diaz-Anderson    travel agency    Travel
1            NaN       Wong, Myers and Peters         hospital    Health
2            NaN             Malone-Mcconnell  physiotherapist    Health
3            NaN             Frazier-Alvarado          rv park     Store
4            NaN  Sweeney, Jones and Reynolds           lawyer   Service

In [4]:
df

Name                    Place name         Place type  \
0         Kevin Vasquez                 Diaz-Anderson      travel agency   
1                   NaN        Wong, Myers and Peters           hospital   
2                   NaN              Malone-Mcconnell    physiotherapist   
3                   NaN              Frazier-Alvarado            rv park   
4                   NaN   Sweeney, Jones and Reynolds             lawyer   
...                 ...                           ...                ...   
9996                NaN     Harris, Edwards and Scott    physiotherapist   
9997                NaN  Robinson, Gordon and Delgado  electronics store   
9998                NaN                     Banks PLC            florist   
9999                NaN                    Frey Group             casino   
10000  Christopher Mack                           NaN                NaN   

        SuperType  
0          Travel  
1          Health  
2          Health  
3           Store  
4         Service  
...           ...  
9996       Health  
9997        Store  
9998          Job  
9999   Recreation  
10000         NaN  

[10001 rows x 4 columns]

In [5]:
Feature = pd.get_dummies(df['SuperType'])

X=Feature[0:50]
Y=Feature[51:100]

X.shape

(50, 11)

In [6]:
X.head()

Finance  Food  Health  Job  Luxury  Recreation  Religious  Service  Store  \
0        0     0       0    0       0           0          0        0      0   
1        0     0       1    0       0           0          0        0      0   
2        0     0       1    0       0           0          0        0      0   
3        0     0       0    0       0           0          0        0      1   
4        0     0       0    0       0           0          0        1      0   

   Study  Travel  
0      0       1  
1      0       0  
2      0       0  
3      0       0  
4      0       0

In [7]:
X=X.sum(axis=0)

Y=Y.sum(axis=0)

X

Finance        2
Food           4
Health         7
Job            3
Luxury         2
Recreation    10
Religious      3
Service        9
Store          9
Study          0
Travel         1
dtype: int64

In [8]:
x=X.to_numpy()
x
y=Y.to_numpy()
x=x.reshape(1,-1)
y=y.reshape(1,-1)
x,y

(array([[ 2,  4,  7,  3,  2, 10,  3,  9,  9,  0,  1]], dtype=int64),
 array([[ 1,  0,  2,  2,  1,  7,  0, 11, 20,  1,  4]], dtype=int64))

# Cosine Similarity

In [9]:

from sklearn.metrics.pairwise import cosine_similarity
a = (cosine_similarity(x,y))
print(a[0])

[0.82007308]


# Pearson Correlation

In [10]:
from scipy.stats import pearsonr
corr,_=pearsonr(X,Y)
print(corr)

0.7041915714276278


In [19]:
n=20

X = Feature[(n*50)+1:(n+1)*50]
X = X.sum(axis = 0)
X
x=X.to_numpy()
x = x.reshape(1,-1)
Y = Feature[0:50]
Y = Y.sum(axis = 0)
y=Y.to_numpy()
y = y.reshape(1,-1)
x,y

(array([[ 1,  1,  2,  4,  4,  7,  1,  3, 21,  2,  3]], dtype=int64),
 array([[ 2,  4,  7,  3,  2, 10,  3,  9,  9,  0,  1]], dtype=int64))

In [20]:
m = cosine_similarity(x,y)
m[0][0]

0.7517278724791983

In [21]:
m,_ = pearsonr(X,Y)
m

0.5321481272249868